### ISSUE TITLE
info button does not work on webkit browsers

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/existdb-packagemanager#7]
the blue info button does not expand and display the panel as expected, it works in firefox. 

tested with Safari `11.1.1` 
and Chrome `67.0.3396.87`

**Comment by JoernT** [comment]
Of course i tested this with mentioned browsers but will check again tomorrow.

**Comment by dizzzz** [comment]
@duncdrum  Can you share a screenshot? what about a 'show details/errors' list from the dev tools in the browser?

**Comment by duncdrum** [comment]
![ezgif com-optimize](https://user-images.githubusercontent.com/6205362/41395968-d6a446ee-6faf-11e8-8e78-b5d434ce74df.gif)
Video uses safari tech preview (no plugins). Tested on 4.2.1 and 5.0.0-RC1, all tests on macOS 10.13.5. 

I don't think the favicon warning is it,  the missing webcomponents-lite.js.map could be to blame. 

The warning of screen is:
```
[Deprecation] The “vaadin-valo-styles” (previously named “vaadin-valo-theme”) package is deprecated. Please migrate to the “vaadin-lumo-styles” package. See "https://github.com/vaadin/vaadin-valo-styles/blob/master/README.md" for more information.
```

@JoernT have you considered sauce labs to specify an array of supported browsers for testing? How about `wct.conf.json` as recommended by the polymer2 [docs](https://www.polymer-project.org/2.0/docs/tools/tests) for [testing](https://github.com/Polymer/tools/tree/master/packages/web-component-tester) webcomponents.

**Comment by JoernT** [comment]
seems to be a regression. Pretty sure it worked. Neither of the above warnings will be responsible. I think it's an event-handling issue. Will have a look.

@duncdrum sourcelabs won't help a lot as there are no tests yet ;) Further this kind of issue is not new to me. There are differences between FF and Chrome/Safari with respect to event-handling that nagged me before but the cause is the differences in shadowDOM implementations. This is likely going away soon as FF will roll out shadowDOM in the very near future.

But of course i'd like to add tests anyway when i find the time.

**Comment by JoernT** [comment]
arrgh - it's worse. It is NOT the event-handling but the different handling of CSS matchers - still investigating...

**Comment by JoernT** [comment]
I'm stuck with this issue at the moment. Seems it's a kind of refreshing problem with CSS. When the icon is clicked an attribute is set on a wrapper element which should fire a CSS style that makes the subitems visible. For some reason this not working (any more). Maybe the <repo-element> and it's descendants don't have the best design and it needs a rewrite but that would be a larger effort. Still hoping for an easier fix.

**Comment by JoernT** [comment]
one step further - got it working in Chrome but not Safari.
